<!-- html -->
<template>
  <fx-space :size="[10, 10]">
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
    <fx-button>按钮</fx-button>
  </fx-space>
</template>
