/* Automatically generated by '../script/build-entry.js' */

import fButton from './button/index.js';
import fConfirm from './confirm/index.js';
import fCheckbox from './checkbox/index.js';
import fDrawer from './drawer/index.js';
import fLoading from './loading/index.js';
import fDropDown from './dropDown/index.js';
import fInput from './input/index.js';
import fOptfile from './optfile/index.js';
import fModal from './modal/index.js';
import fSelect from './select/index.js';
import fMessage from './message/index.js';
import fTree from './tree/index.js';
import fTable from './table/index.js';
import fSwitch from './switch/index.js';
import fRadio from './radio/index.js';
// 版本号
import pkg from '../package.json'


const components = [
    fButton,
  fCheckbox,
  fDrawer,
  fDropDown,
  fInput,
  fOptfile,
  fModal,
  fSelect,
  fTree,
  fTable,
  fSwitch,
  fRadio
];

const install = (app) => {
  components.forEach((i) => {
    app.use(i)
  })
    app.config.globalProperties.$confirm = fConfirm
  app.config.globalProperties.$loading = fLoading
  app.config.globalProperties.$message = fMessage
}

const fxUi = {
  version: pkg.version,
  install
}

export {
  install,
    fButton,
  fConfirm,
  fCheckbox,
  fDrawer,
  fLoading,
  fDropDown,
  fInput,
  fOptfile,
  fModal,
  fSelect,
  fMessage,
  fTree,
  fTable,
  fSwitch,
  fRadio
}

export default fxUi
